Repository PolicyEngine/policyengine, pull requests merged in 2022-03, with the labels that each got.

#521 Bug fixes and openfisca-uk bump
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/components/autoUBI.jsx
  policyengine-client/src/policyengine/pages/policy/parameter.jsx
  policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
  policyengine-client/src/policyengine/tools/translation.jsx
  policyengine/__init__.py
  policyengine/impact/household/charts.py
  setup.py
Labels: ui

#529 Add Social Security inputs and reorganize personal benefits
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/us/us.jsx
  policyengine/__init__.py
  policyengine/monitoring/watched_reforms.md
  setup.py
Labels: us

#537 Fix AutoUBI and update OpenFisca-UK
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/components/autoUBI.jsx
  policyengine-client/src/countries/uk/uk.jsx
  policyengine/__init__.py
  policyengine/utils/reforms.py
  setup.py
Labels: uk

#539 Prevent users changing US state
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/country.jsx
  policyengine-client/src/countries/uk/components/faq.md
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/markdown/uk/faq.md
  policyengine-client/src/policyengine/pages/household/accountingTable.jsx
  policyengine-client/src/policyengine/pages/household/variable.jsx
  policyengine-client/src/policyengine/policyengine.jsx
  policyengine/__init__.py
  policyengine/countries/country.py
Labels: enhancement

#538 Single/married switch
  .gitignore
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/country.jsx
  policyengine-client/src/countries/debug.jsx
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/policyengine/pages/household/inputPane.jsx
  policyengine/__init__.py
Labels: ui

#542 YAML changelog
  .github/changelog_template.md
  .github/get-changelog-diff.sh
  .github/is-version-number-acceptable.sh
  .github/pull_request_template.md
  .github/workflows/pr.yml
  .github/workflows/push.yml
  CHANGELOG.md
  Makefile
  changelog.yaml
  setup.py
Labels: code health

#524 Fixed policies height
  changelog.yaml
  policyengine-client/src/policyengine/pages/household/household.jsx
  policyengine-client/src/policyengine/pages/policy/overview.jsx
  policyengine-client/src/policyengine/pages/policy/policy.jsx
  policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
Labels: ui

#550 Enable earnings charts
  changelog.yaml
  policyengine-client/src/countries/us/us.jsx
  policyengine/impact/household/charts.py
  policyengine/tests/server/test_server.py
Labels: household impact, us

#559 Marriage bug
  changelog.yaml
  policyengine-client/src/countries/uk/uk.jsx
Labels: bug

#562 Add debugging logic and bump OpenFisca-US
  changelog.yaml
  policyengine/impact/household/charts.py
Labels: household impact

#563 Bump openfisca-us
  changelog.yaml
  setup.py
Labels: bug

#566 IRS fix
  changelog.yaml
  setup.py
Labels: bug, us

#567 Use USD in US charts
  changelog.yaml
  policyengine/countries/uk/__init__.py
  policyengine/countries/us/__init__.py
  policyengine/impact/household/charts.py
  policyengine/impact/population/breakdown.py
  policyengine/impact/population/charts.py
  policyengine/utils/charts.py
  policyengine/utils/general.py
Labels: enhancement

#581 Fix API bug
  changelog.yaml
  policyengine-client/package.json
  policyengine-client/public/index.html
  policyengine-client/src/App.jsx
  policyengine-client/src/landing.jsx
  policyengine-client/src/policyengine/header/mainNavigation.jsx
  policyengine/countries/country.py
  policyengine/tests/server/situations/test_calculate_endpoint.py
  setup.py
Labels: enhancement

#586 Add counterfactuals
  changelog.yaml
  policyengine-client/public/index.html
  policyengine-client/src/App.jsx
  policyengine-client/src/countries/country.jsx
  policyengine-client/src/countries/uk/components/timeTravel.jsx
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/landing.jsx
  policyengine-client/src/policyengine/general/radioButton.jsx
  policyengine-client/src/policyengine/pages/household/accountingTable.jsx
  policyengine-client/src/policyengine/pages/household/household.jsx
  policyengine-client/src/policyengine/pages/policy/overview.jsx
  policyengine-client/src/policyengine/pages/policy/parameter.jsx
  policyengine-client/src/policyengine/pages/policy/policy.jsx
  policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
  policyengine-client/src/policyengine/policyengine.jsx
  policyengine-client/src/policyengine/tools/url.jsx
  policyengine/countries/country.py
  policyengine/countries/uk/default_reform/reform.py
  policyengine/countries/uk/reform_parameters.yaml
  policyengine/tests/server/populations/test_population_metrics.py
  policyengine/utils/reforms.py
  setup.py
Labels: enhancement

#595 Performance improvements and bug fixes
  changelog.yaml
  policyengine-client/package.json
  policyengine-client/src/App.jsx
  policyengine-client/src/countries/country.jsx
  policyengine-client/src/countries/uk/components/faq.md
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/landing.jsx
  policyengine-client/src/markdown/uk/faq.md
  policyengine-client/src/policyengine/pages/household/accountingTable.jsx
  policyengine-client/src/policyengine/pages/household/earningsCharts.jsx
  policyengine-client/src/policyengine/pages/populationImpact/chart.jsx
  policyengine-client/src/policyengine/policyengine.jsx
  policyengine-client/src/policyengine/tools/translation.jsx
  policyengine/countries/country.py
  policyengine/utils/reforms.py
Labels: enhancement

#601 Add CDCC
  changelog.yaml
  policyengine-client/src/countries/us/us.jsx
  setup.py
Labels: enhancement

#602 Add parameters and last fixes before launch
  changelog.yaml
  policyengine-client/public/index.html
  policyengine-client/public/social_preview/global.png
  policyengine-client/public/social_preview/uk.png
  policyengine-client/public/social_preview/us.png
  policyengine-client/src/countries/country.jsx
  policyengine-client/src/countries/uk/components/timeTravel.jsx
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/policyengine/pages/policy/parameter.jsx
  policyengine/server.py
  policyengine/utils/social_card.py
  setup.py
Labels: enhancement
