Repository PolicyEngine/policyengine, pull requests merged in 2022-02, with the labels that each got.

#453 Add exemption for seniors
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/policyengine/pages/policy/parameter.jsx
  policyengine/__init__.py
  policyengine/countries/uk/default_reform/reform.py
  policyengine/countries/uk/reform_parameters.yaml
Labels: policy, uk

#458 Energy Bills Rebate
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/uk.jsx
  policyengine/__init__.py
  setup.py
Labels: policy, uk

#462 Fix right sidebar
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/policyengine/pages/household/household.jsx
  policyengine-client/src/policyengine/pages/policy/overview.jsx
  policyengine-client/src/policyengine/pages/policy/policy.jsx
  policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
  policyengine/__init__.py
Labels: ui

#486 Fix UK table
  .github/workflows/push.yml
  CHANGELOG.md
  Makefile
  policyengine-client/package.json
  policyengine-client/src/countries/uk/uk.jsx
  policyengine/__init__.py
Labels: ui

#496 Add basic income controls
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/components/autoUBI.jsx
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/policyengine/policyengine.jsx
  policyengine-client/src/policyengine/tools/url.jsx
  policyengine/__init__.py
  policyengine/countries/uk/default_reform/reform.py
  policyengine/utils/reforms.py
  setup.py
Labels: policy, uk

#492 Add breakdown parameter
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/policyengine/pages/policy/parameter.jsx
  policyengine/__init__.py
  policyengine/utils/reforms.py
  setup.py
Labels: ui, policy

#500 UI fixes
  .github/workflows/pr.yml
  .github/workflows/push.yml
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/uk/uk.jsx
  policyengine-client/src/images/clock.png
  policyengine-client/src/images/misc.png
  policyengine-client/src/policyengine/pages/household/accountingTable.jsx
  policyengine/__init__.py
  policyengine/impact/household/charts.py
  setup.py
Labels: ui

#505 UI fixes
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/countries/us/us.jsx
  policyengine-client/src/policyengine/pages/household/accountingTable.jsx
  policyengine-client/src/policyengine/pages/household/household.jsx
  policyengine-client/src/policyengine/pages/policy/policy.jsx
  policyengine/__init__.py
Labels: ui

#518 Hide legend from household charts when no reform
  CHANGELOG.md
  policyengine-client/package.json
  policyengine-client/src/policyengine/pages/populationImpact/populationImpact.jsx
  policyengine/__init__.py
  policyengine/impact/household/charts.py
  policyengine/impact/population/charts.py
  setup.py
Labels: ui
